/* 부서테이블 */
--DROP TABLE DEPT CASCADE CONSTRAINTS;
CREATE TABLE DEPT (
	DEPT_NO NUMBER UNIQUE NOT NULL, /* 부서코드 */
	DEPT_NAME VARCHAR2(100) NOT NULL, /* 부서명 */
	UPPER_DEPT_NO NUMBER /* 상위부서코드 */
);

COMMENT ON TABLE DEPT IS '부서테이블';

COMMENT ON COLUMN DEPT.DEPT_NO IS '부서코드';

COMMENT ON COLUMN DEPT.DEPT_NAME IS '부서명';

COMMENT ON COLUMN DEPT.UPPER_DEPT_NO IS '상위부서코드';

CREATE UNIQUE INDEX PK_DEPT
	ON DEPT (
		DEPT_NO ASC
	);

ALTER TABLE DEPT
	ADD
		CONSTRAINT PK_DEPT
		PRIMARY KEY (
			DEPT_NO
		);
        
--DROP SEQUENCE DEPT_SEQ;
--CREATE SEQUENCE DEPT_SEQ
--START WITH 1
--INCREMENT BY 1
--NOCACHE;

INSERT INTO DEPT(DEPT_NO, DEPT_NAME)
VALUES(101, 'EZ그룹');

INSERT INTO DEPT(DEPT_NO, DEPT_NAME, UPPER_DEPT_NO)
VALUES(201, '영업본부', 101);
INSERT INTO DEPT(DEPT_NO, DEPT_NAME, UPPER_DEPT_NO)
VALUES(202, '경영지원본부', 101);
INSERT INTO DEPT(DEPT_NO, DEPT_NAME, UPPER_DEPT_NO)
VALUES(203, '개발본부', 101);
INSERT INTO DEPT(DEPT_NO, DEPT_NAME, UPPER_DEPT_NO)
VALUES(204, '서비스본부', 101);

INSERT INTO DEPT(DEPT_NO, DEPT_NAME, UPPER_DEPT_NO)
VALUES(301, '영업팀', 201);
INSERT INTO DEPT(DEPT_NO, DEPT_NAME, UPPER_DEPT_NO)
VALUES(302, '마케팅팀', 201);

INSERT INTO DEPT(DEPT_NO, DEPT_NAME, UPPER_DEPT_NO)
VALUES(303, '재경팀', 202);
INSERT INTO DEPT(DEPT_NO, DEPT_NAME, UPPER_DEPT_NO)
VALUES(304, '총무팀', 202);
INSERT INTO DEPT(DEPT_NO, DEPT_NAME, UPPER_DEPT_NO)
VALUES(305, '인사팀', 202);

INSERT INTO DEPT(DEPT_NO, DEPT_NAME, UPPER_DEPT_NO)
VALUES(306, '서비스개발팀', 203);
INSERT INTO DEPT(DEPT_NO, DEPT_NAME, UPPER_DEPT_NO)
VALUES(307, '플랫폼운영팀', 203);
INSERT INTO DEPT(DEPT_NO, DEPT_NAME, UPPER_DEPT_NO)
VALUES(308, '디자인팀', 203);

INSERT INTO DEPT(DEPT_NO, DEPT_NAME, UPPER_DEPT_NO)
VALUES(309, '인터넷사업팀', 204);
INSERT INTO DEPT(DEPT_NO, DEPT_NAME, UPPER_DEPT_NO)
VALUES(310, '커머스사업팀', 204);

