/* 직급테이블 */
--DROP TABLE POSITION CASCADE CONSTRAINTS;
CREATE TABLE POSITION (
	POS_NO NUMBER NOT NULL, /* 직급번호 */
	POS_NAME VARCHAR2(50) NOT NULL, /* 직급명 */
	POS_PRIORITY NUMBER NOT NULL /* 직급순서 */
);

COMMENT ON TABLE POSITION IS '직급테이블';

COMMENT ON COLUMN POSITION.POS_NO IS '직급번호';

COMMENT ON COLUMN POSITION.POS_NAME IS '직급명';

COMMENT ON COLUMN POSITION.POS_PRIORITY IS '직급순서';

CREATE UNIQUE INDEX PK_POSITION
	ON POSITION (
		POS_NO ASC
	);

ALTER TABLE POSITION
	ADD
		CONSTRAINT PK_POSITION
		PRIMARY KEY (
			POS_NO
		);

CREATE SEQUENCE POS_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

INSERT INTO POSITION(POS_NO, POS_NAME, POS_PRIORITY)
VALUES(POS_SEQ.NEXTVAL, '대표이사', 1);
INSERT INTO POSITION(POS_NO, POS_NAME, POS_PRIORITY)
VALUES(POS_SEQ.NEXTVAL, '사장', 2);
INSERT INTO POSITION(POS_NO, POS_NAME, POS_PRIORITY)
VALUES(POS_SEQ.NEXTVAL, '전무', 3);
INSERT INTO POSITION(POS_NO, POS_NAME, POS_PRIORITY)
VALUES(POS_SEQ.NEXTVAL, '상무', 4);
INSERT INTO POSITION(POS_NO, POS_NAME, POS_PRIORITY)
VALUES(POS_SEQ.NEXTVAL, '이사', 5);
INSERT INTO POSITION(POS_NO, POS_NAME, POS_PRIORITY)
VALUES(POS_SEQ.NEXTVAL, '감사', 6);
INSERT INTO POSITION(POS_NO, POS_NAME, POS_PRIORITY)
VALUES(POS_SEQ.NEXTVAL, '부장', 7);
INSERT INTO POSITION(POS_NO, POS_NAME, POS_PRIORITY)
VALUES(POS_SEQ.NEXTVAL, '차장', 8);
INSERT INTO POSITION(POS_NO, POS_NAME, POS_PRIORITY)
VALUES(POS_SEQ.NEXTVAL, '과장', 9);
INSERT INTO POSITION(POS_NO, POS_NAME, POS_PRIORITY)
VALUES(POS_SEQ.NEXTVAL, '대리', 10);
INSERT INTO POSITION(POS_NO, POS_NAME, POS_PRIORITY)
VALUES(POS_SEQ.NEXTVAL, '계장', 11);
INSERT INTO POSITION(POS_NO, POS_NAME, POS_PRIORITY)
VALUES(POS_SEQ.NEXTVAL, '사원', 12);


--여기는 필요없는 부분
--SELECT * FROM POSITION;
--
--select * from emp_posting;
--select * from board;
--select * from posting;
--select * from emp;
--select * from dept;
--select * from position;
--select P.POSTING_TITLE, P.POSTING_CONTENT, P.POSTING_REGDATE, E.EMP_NAME, E.EMP_NO, E.POS_NO,P.BOARD_NO 
--        from posting p 
--        left join emp e on p.emp_no = e.emp_no;
--    
--SELECT * FROM BOARD;
--
--SELECT C.*, V.POS_NAME
--FROM (SELECT B.*, W.DEPT_NAME
--      FROM (SELECT A.*, X.BOARD_NAME, X.BOARD_TYPE, X.DEPT_NO
--            FROM (SELECT Z.POSTING_NO, Z.POSTING_TITLE, Z.POSTING_CONTENT, Z.POSTING_REGDATE, Z.EMP_NO, Z.BOARD_NO, Y.EMP_NAME, Y.EMP_IMG, Y.POS_NO
--                  FROM POSTING Z 
--                  LEFT JOIN EMP Y ON Z.EMP_NO = Y.EMP_NO)A 
--            LEFT JOIN BOARD X ON A.BOARD_NO=X.BOARD_NO)B 
--      LEFT JOIN DEPT W ON B.DEPT_NO = W.DEPT_NO)C 
--LEFT JOIN POSITION V ON C.POS_NO = V.POS_NO;
--
--select * from (select * from posting a left join emp b on a.emp_no=b.emp_no)c left join board d on c.board_no = d.board_no;
--
--select * from posting_files;